//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// DomainClass Tapiz
	/// The root in which all other elements are embedded. Appears as a diagram.
	/// </summary>
	[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.Tapiz.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.Tapiz.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("bd527935-6df8-4ad3-adf4-5bf7844d65bc")]
	public partial class Tapiz : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Tapiz domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xbd527935, 0x6df8, 0x4ad3, 0xad, 0xf4, 0x5b, 0xf7, 0x84, 0x4d, 0x65, 0xbc);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Tapiz(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Tapiz(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Entidad opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Entidad.
		/// Description for IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad.Tapiz
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Entidad> Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad.TapizDomainRoleId);
			}
		}
		#endregion
		#region Relacioned opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Relacioned.
		/// Description for IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned.Tapiz
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Relacion> Relacioned
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned.TapizDomainRoleId);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::IPS_GT16.XCXABGProyectoIPS.Entidad.DomainClassId)) 
				{
					return true;
				}
				
				if (rootElementDomainInfo.IsDerivedFrom(global::IPS_GT16.XCXABGProyectoIPS.Relacion.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::IPS_GT16.XCXABGProyectoIPS.Entidad sourceEntidad1 = sourceElement as global::IPS_GT16.XCXABGProyectoIPS.Entidad;
			if (sourceEntidad1 != null)
			{
				// Create link for path TapizHasEntidad.Entidad
				this.Entidad.Add(sourceEntidad1);

				return;
			}
				
			global::IPS_GT16.XCXABGProyectoIPS.Relacion sourceRelacion2 = sourceElement as global::IPS_GT16.XCXABGProyectoIPS.Relacion;
			if (sourceRelacion2 != null)
			{
				// Create link for path TapizHasRelacioned.Relacioned
				this.Relacioned.Add(sourceRelacion2);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::IPS_GT16.XCXABGProyectoIPS.Entidad sourceEntidad1 = sourceElement as global::IPS_GT16.XCXABGProyectoIPS.Entidad;
			if (sourceEntidad1 != null)
			{
				// Delete link for path TapizHasEntidad.Entidad
				
				foreach (DslModeling::ElementLink link in global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad.GetLinks((global::IPS_GT16.XCXABGProyectoIPS.Tapiz)this, sourceEntidad1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad.TapizDomainRoleId, global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad.EntidadDomainRoleId);
				}

				return;
			}
				
			global::IPS_GT16.XCXABGProyectoIPS.Relacion sourceRelacion2 = sourceElement as global::IPS_GT16.XCXABGProyectoIPS.Relacion;
			if (sourceRelacion2 != null)
			{
				// Delete link for path TapizHasRelacioned.Relacioned
				
				foreach (DslModeling::ElementLink link in global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned.GetLinks((global::IPS_GT16.XCXABGProyectoIPS.Tapiz)this, sourceRelacion2))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned.TapizDomainRoleId, global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned.RelacionDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// DomainClass Entidad
	/// Description for IPS_GT16.XCXABGProyectoIPS.Entidad
	/// </summary>
	[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.Entidad.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.Entidad.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("02fd950c-3e8e-401e-acb7-1766060875b5")]
	public partial class Entidad : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Entidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x02fd950c, 0x3e8e, 0x401e, 0xac, 0xb7, 0x17, 0x66, 0x06, 0x08, 0x75, 0xb5);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Entidad(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Entidad(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Name domain property code
		
		/// <summary>
		/// Name domain property Id.
		/// </summary>
		public static readonly global::System.Guid NameDomainPropertyId = new global::System.Guid(0xdb359947, 0xcd49, 0x4c03, 0xb7, 0x26, 0x55, 0xc2, 0x88, 0x80, 0x50, 0x28);
		
		/// <summary>
		/// Storage for Name
		/// </summary>
		private global::System.String namePropertyStorage = "Entidad";
		
		/// <summary>
		/// Gets or sets the value of Name domain property.
		/// Description for IPS_GT16.XCXABGProyectoIPS.Entidad.Name
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.Entidad/Name.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.Entidad/Name.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue("Entidad")]
		[DslModeling::DomainObjectId("db359947-cd49-4c03-b726-55c288805028")]
		public global::System.String Name
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return namePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				NamePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Entidad.Name domain property.
		/// </summary>
		internal sealed partial class NamePropertyHandler : DslModeling::DomainPropertyValueHandler<Entidad, global::System.String>
		{
			private NamePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Entidad.Name domain property value handler.
			/// </summary>
			public static readonly NamePropertyHandler Instance = new NamePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Entidad.Name domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return NameDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Entidad element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.namePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Entidad element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.namePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Tapiz opposite domain role accessor
		/// <summary>
		/// Gets or sets Tapiz.
		/// Description for IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad.Entidad
		/// </summary>
		public virtual Tapiz Tapiz
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad.EntidadDomainRoleId) as Tapiz;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad.EntidadDomainRoleId, value);
			}
		}
		#endregion
		#region Relacioned opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Relacioned.
		/// Description for IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned.Entidad
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Relacion> Relacioned
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned.EntidadDomainRoleId);
			}
		}
		#endregion
		#region ClavePrimaria opposite domain role accessor
		/// <summary>
		/// Gets or sets ClavePrimaria.
		/// Description for IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.Entidad
		/// </summary>
		public virtual ClavePrimaria ClavePrimaria
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.EntidadDomainRoleId) as ClavePrimaria;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.EntidadDomainRoleId, value);
			}
		}
		#endregion
		#region AtributoEntidad opposite domain role accessor
		
		/// <summary>
		/// Gets a list of AtributoEntidad.
		/// Description for IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad.Entidad
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<AtributoEntidad> AtributoEntidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoEntidad>, AtributoEntidad>(global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad.EntidadDomainRoleId);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::IPS_GT16.XCXABGProyectoIPS.ClavePrimaria.DomainClassId)) 
				{
					// Check that creating a link with this path doesn't cause multiplicity overflow: EntidadHasClavePrimaria.ClavePrimaria
					if (this.ClavePrimaria != null)
					{
						return false;
					}
					return true;
				}
				
				if (rootElementDomainInfo.IsDerivedFrom(global::IPS_GT16.XCXABGProyectoIPS.AtributoEntidad.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::IPS_GT16.XCXABGProyectoIPS.ClavePrimaria sourceClavePrimaria1 = sourceElement as global::IPS_GT16.XCXABGProyectoIPS.ClavePrimaria;
			if (sourceClavePrimaria1 != null)
			{
				// Create link for path EntidadHasClavePrimaria.ClavePrimaria
				this.ClavePrimaria = sourceClavePrimaria1;

				return;
			}
				
			global::IPS_GT16.XCXABGProyectoIPS.AtributoEntidad sourceAtributoEntidad2 = sourceElement as global::IPS_GT16.XCXABGProyectoIPS.AtributoEntidad;
			if (sourceAtributoEntidad2 != null)
			{
				// Create link for path EntidadHasAtributoEntidad.AtributoEntidad
				this.AtributoEntidad.Add(sourceAtributoEntidad2);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::IPS_GT16.XCXABGProyectoIPS.ClavePrimaria sourceClavePrimaria1 = sourceElement as global::IPS_GT16.XCXABGProyectoIPS.ClavePrimaria;
			if (sourceClavePrimaria1 != null)
			{
				// Delete link for path EntidadHasClavePrimaria.ClavePrimaria
				
				foreach (DslModeling::ElementLink link in global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.GetLinks((global::IPS_GT16.XCXABGProyectoIPS.Entidad)this, sourceClavePrimaria1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.EntidadDomainRoleId, global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.ClavePrimariaDomainRoleId);
				}

				return;
			}
				
			global::IPS_GT16.XCXABGProyectoIPS.AtributoEntidad sourceAtributoEntidad2 = sourceElement as global::IPS_GT16.XCXABGProyectoIPS.AtributoEntidad;
			if (sourceAtributoEntidad2 != null)
			{
				// Delete link for path EntidadHasAtributoEntidad.AtributoEntidad
				
				foreach (DslModeling::ElementLink link in global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad.GetLinks((global::IPS_GT16.XCXABGProyectoIPS.Entidad)this, sourceAtributoEntidad2))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad.EntidadDomainRoleId, global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// DomainClass Relacion
	/// Description for IPS_GT16.XCXABGProyectoIPS.Relacion
	/// </summary>
	[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.Relacion.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.Relacion.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("0d0b00f2-3b41-4130-b818-65afcb5b6f60")]
	public partial class Relacion : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Relacion domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x0d0b00f2, 0x3b41, 0x4130, 0xb8, 0x18, 0x65, 0xaf, 0xcb, 0x5b, 0x6f, 0x60);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Relacion(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Relacion(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Name domain property code
		
		/// <summary>
		/// Name domain property Id.
		/// </summary>
		public static readonly global::System.Guid NameDomainPropertyId = new global::System.Guid(0xe65b0dbc, 0xc5ea, 0x4b39, 0xa3, 0x61, 0xef, 0x2b, 0xb3, 0xc6, 0xd3, 0x52);
		
		/// <summary>
		/// Storage for Name
		/// </summary>
		private global::System.String namePropertyStorage = "NombreRelacion";
		
		/// <summary>
		/// Gets or sets the value of Name domain property.
		/// Description for IPS_GT16.XCXABGProyectoIPS.Relacion.Name
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.Relacion/Name.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.Relacion/Name.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue("NombreRelacion")]
		[DslModeling::DomainObjectId("e65b0dbc-c5ea-4b39-a361-ef2bb3c6d352")]
		public global::System.String Name
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return namePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				NamePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Relacion.Name domain property.
		/// </summary>
		internal sealed partial class NamePropertyHandler : DslModeling::DomainPropertyValueHandler<Relacion, global::System.String>
		{
			private NamePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Relacion.Name domain property value handler.
			/// </summary>
			public static readonly NamePropertyHandler Instance = new NamePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Relacion.Name domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return NameDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Relacion element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.namePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Relacion element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.namePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Entidad opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Entidad.
		/// Description for IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned.Relacion
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Entidad> Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned.RelacionDomainRoleId);
			}
		}
		#endregion
		#region Tapiz opposite domain role accessor
		/// <summary>
		/// Gets or sets Tapiz.
		/// Description for IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned.Relacion
		/// </summary>
		public virtual Tapiz Tapiz
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned.RelacionDomainRoleId) as Tapiz;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned.RelacionDomainRoleId, value);
			}
		}
		#endregion
		#region AtributoRelacion opposite domain role accessor
		
		/// <summary>
		/// Gets a list of AtributoRelacion.
		/// Description for IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion.Relacion
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<AtributoRelacion> AtributoRelacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoRelacion>, AtributoRelacion>(global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion.RelacionDomainRoleId);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::IPS_GT16.XCXABGProyectoIPS.AtributoRelacion.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::IPS_GT16.XCXABGProyectoIPS.AtributoRelacion sourceAtributoRelacion1 = sourceElement as global::IPS_GT16.XCXABGProyectoIPS.AtributoRelacion;
			if (sourceAtributoRelacion1 != null)
			{
				// Create link for path RelacionHasAtributoRelacion.AtributoRelacion
				this.AtributoRelacion.Add(sourceAtributoRelacion1);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::IPS_GT16.XCXABGProyectoIPS.AtributoRelacion sourceAtributoRelacion1 = sourceElement as global::IPS_GT16.XCXABGProyectoIPS.AtributoRelacion;
			if (sourceAtributoRelacion1 != null)
			{
				// Delete link for path RelacionHasAtributoRelacion.AtributoRelacion
				
				foreach (DslModeling::ElementLink link in global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion.GetLinks((global::IPS_GT16.XCXABGProyectoIPS.Relacion)this, sourceAtributoRelacion1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion.RelacionDomainRoleId, global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion.AtributoRelacionDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// DomainClass Atributo
	/// Description for IPS_GT16.XCXABGProyectoIPS.Atributo
	/// </summary>
	[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.Atributo.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.Atributo.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("e2ca1ce5-0f0a-4d12-858f-ccc0bf5614f4")]
	public partial class Atributo : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Atributo domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xe2ca1ce5, 0x0f0a, 0x4d12, 0x85, 0x8f, 0xcc, 0xc0, 0xbf, 0x56, 0x14, 0xf4);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Atributo(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Atributo(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Nombre domain property code
		
		/// <summary>
		/// Nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid NombreDomainPropertyId = new global::System.Guid(0xd16d60ff, 0x180f, 0x47b9, 0x96, 0x2b, 0x7b, 0x5d, 0x90, 0x57, 0x91, 0x6b);
		
		/// <summary>
		/// Storage for Nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = "Name";
		
		/// <summary>
		/// Gets or sets the value of Nombre domain property.
		/// Description for IPS_GT16.XCXABGProyectoIPS.Atributo.Nombre
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.Atributo/Nombre.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.Atributo/Nombre.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue("Name")]
		[DslModeling::DomainObjectId("d16d60ff-180f-47b9-962b-7b5d9057916b")]
		public global::System.String Nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				NombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Atributo.Nombre domain property.
		/// </summary>
		internal sealed partial class NombrePropertyHandler : DslModeling::DomainPropertyValueHandler<Atributo, global::System.String>
		{
			private NombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Atributo.Nombre domain property value handler.
			/// </summary>
			public static readonly NombrePropertyHandler Instance = new NombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Atributo.Nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return NombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Atributo element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Atributo element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region LongitudDato domain property code
		
		/// <summary>
		/// LongitudDato domain property Id.
		/// </summary>
		public static readonly global::System.Guid LongitudDatoDomainPropertyId = new global::System.Guid(0xed545bcf, 0xd0d4, 0x41c2, 0x83, 0xf7, 0x44, 0x06, 0xf7, 0x42, 0xe1, 0xe6);
		
		/// <summary>
		/// Storage for LongitudDato
		/// </summary>
		private global::System.Int16 longitudDatoPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of LongitudDato domain property.
		/// Description for IPS_GT16.XCXABGProyectoIPS.Atributo.Longitud Dato
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.Atributo/LongitudDato.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.Atributo/LongitudDato.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("ed545bcf-d0d4-41c2-83f7-4406f742e1e6")]
		public global::System.Int16 LongitudDato
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return longitudDatoPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				LongitudDatoPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Atributo.LongitudDato domain property.
		/// </summary>
		internal sealed partial class LongitudDatoPropertyHandler : DslModeling::DomainPropertyValueHandler<Atributo, global::System.Int16>
		{
			private LongitudDatoPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Atributo.LongitudDato domain property value handler.
			/// </summary>
			public static readonly LongitudDatoPropertyHandler Instance = new LongitudDatoPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Atributo.LongitudDato domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return LongitudDatoDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.Int16 GetValue(Atributo element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.longitudDatoPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Atributo element, global::System.Int16 newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.Int16 oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.longitudDatoPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region NameTipo domain property code
		
		/// <summary>
		/// NameTipo domain property Id.
		/// </summary>
		public static readonly global::System.Guid NameTipoDomainPropertyId = new global::System.Guid(0x4ef0ba9d, 0x68d4, 0x4683, 0xb6, 0x0e, 0x60, 0xff, 0x7b, 0xa2, 0x5d, 0x76);
		
		/// <summary>
		/// Gets or sets the value of NameTipo domain property.
		/// Description for IPS_GT16.XCXABGProyectoIPS.Atributo.Name Tipo
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.Atributo/NameTipo.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.Atributo/NameTipo.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.Browsable(false)]
		[global::System.ComponentModel.ReadOnly(true)]
		[DslModeling::DomainProperty(Kind = DslModeling::DomainPropertyKind.Calculated)]
		[DslModeling::DomainObjectId("4ef0ba9d-68d4-4683-b60e-60ff7ba25d76")]
		public global::System.String NameTipo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return NameTipoPropertyHandler.Instance.GetValue(this);
			}
		}
		/// <summary>
		/// Value handler for the Atributo.NameTipo domain property.
		/// </summary>
		internal sealed partial class NameTipoPropertyHandler : DslModeling::CalculatedPropertyValueHandler<Atributo, global::System.String>
		{
			private NameTipoPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Atributo.NameTipo domain property value handler.
			/// </summary>
			public static readonly NameTipoPropertyHandler Instance = new NameTipoPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Atributo.NameTipo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return NameTipoDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Atributo element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				// There is no storage for NameTipo because its Kind is
				// set to Calculated. Please provide the GetNameTipoValue()
				// method on the domain class.
				return element.GetNameTipoValue();
			}
		
		}
		
		#endregion
		#region TipoDato domain property code
		
		/// <summary>
		/// TipoDato domain property Id.
		/// </summary>
		public static readonly global::System.Guid TipoDatoDomainPropertyId = new global::System.Guid(0x49b5cc08, 0xd170, 0x4625, 0xbc, 0xb5, 0xd5, 0x2e, 0xcb, 0x4d, 0xe5, 0x26);
		
		/// <summary>
		/// Storage for TipoDato
		/// </summary>
		private datos tipoDatoPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of TipoDato domain property.
		/// Description for IPS_GT16.XCXABGProyectoIPS.Atributo.Tipo Dato
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.Atributo/TipoDato.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.Atributo/TipoDato.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("49b5cc08-d170-4625-bcb5-d52ecb4de526")]
		public datos TipoDato
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return tipoDatoPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				TipoDatoPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Atributo.TipoDato domain property.
		/// </summary>
		internal sealed partial class TipoDatoPropertyHandler : DslModeling::DomainPropertyValueHandler<Atributo, datos>
		{
			private TipoDatoPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Atributo.TipoDato domain property value handler.
			/// </summary>
			public static readonly TipoDatoPropertyHandler Instance = new TipoDatoPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Atributo.TipoDato domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return TipoDatoDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed datos GetValue(Atributo element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.tipoDatoPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Atributo element, datos newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				datos oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.tipoDatoPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region letraSize domain property code
		
		/// <summary>
		/// letraSize domain property Id.
		/// </summary>
		public static readonly global::System.Guid letraSizeDomainPropertyId = new global::System.Guid(0xb3882d91, 0x6410, 0x4136, 0x88, 0x55, 0xe9, 0x39, 0x66, 0x4c, 0x95, 0xce);
		
		/// <summary>
		/// Storage for letraSize
		/// </summary>
		private global::System.Int16 letraSizePropertyStorage = 8;
		
		/// <summary>
		/// Gets or sets the value of letraSize domain property.
		/// Description for IPS_GT16.XCXABGProyectoIPS.Atributo.Letra Size
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.Atributo/letraSize.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.Atributo/letraSize.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue(8)]
		[DslModeling::DomainObjectId("b3882d91-6410-4136-8855-e939664c95ce")]
		public global::System.Int16 letraSize
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return letraSizePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				letraSizePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Atributo.letraSize domain property.
		/// </summary>
		internal sealed partial class letraSizePropertyHandler : DslModeling::DomainPropertyValueHandler<Atributo, global::System.Int16>
		{
			private letraSizePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Atributo.letraSize domain property value handler.
			/// </summary>
			public static readonly letraSizePropertyHandler Instance = new letraSizePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Atributo.letraSize domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return letraSizeDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.Int16 GetValue(Atributo element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.letraSizePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Atributo element, global::System.Int16 newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.Int16 oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.letraSizePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region colorLetra domain property code
		
		/// <summary>
		/// colorLetra domain property Id.
		/// </summary>
		public static readonly global::System.Guid colorLetraDomainPropertyId = new global::System.Guid(0x602f0636, 0x870f, 0x4fac, 0x92, 0x1e, 0x45, 0x15, 0x87, 0x6b, 0xbf, 0x3a);
		
		/// <summary>
		/// Storage for colorLetra
		/// </summary>
		private global::System.String colorLetraPropertyStorage = "#000000";
		
		/// <summary>
		/// Gets or sets the value of colorLetra domain property.
		/// Description for IPS_GT16.XCXABGProyectoIPS.Atributo.Color Letra
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.Atributo/colorLetra.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.Atributo/colorLetra.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue("#000000")]
		[DslModeling::DomainObjectId("602f0636-870f-4fac-921e-4515876bbf3a")]
		public global::System.String colorLetra
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return colorLetraPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				colorLetraPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Atributo.colorLetra domain property.
		/// </summary>
		internal sealed partial class colorLetraPropertyHandler : DslModeling::DomainPropertyValueHandler<Atributo, global::System.String>
		{
			private colorLetraPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Atributo.colorLetra domain property value handler.
			/// </summary>
			public static readonly colorLetraPropertyHandler Instance = new colorLetraPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Atributo.colorLetra domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return colorLetraDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Atributo element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.colorLetraPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Atributo element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.colorLetraPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
	}
}
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// DomainClass ClavePrimaria
	/// Description for IPS_GT16.XCXABGProyectoIPS.ClavePrimaria
	/// </summary>
	[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.ClavePrimaria.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.ClavePrimaria.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("27832cf7-3070-424a-a2ec-2615b11ec62c")]
	public partial class ClavePrimaria : Atributo
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// ClavePrimaria domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x27832cf7, 0x3070, 0x424a, 0xa2, 0xec, 0x26, 0x15, 0xb1, 0x1e, 0xc6, 0x2c);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public ClavePrimaria(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public ClavePrimaria(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region esNulo domain property code
		
		/// <summary>
		/// esNulo domain property Id.
		/// </summary>
		public static readonly global::System.Guid esNuloDomainPropertyId = new global::System.Guid(0xa19f234c, 0xcab5, 0x4d2c, 0x92, 0x07, 0x74, 0xbe, 0x19, 0x1a, 0xa1, 0xdf);
		
		/// <summary>
		/// Storage for esNulo
		/// </summary>
		private global::System.String esNuloPropertyStorage = "false";
		
		/// <summary>
		/// Gets or sets the value of esNulo domain property.
		/// Description for IPS_GT16.XCXABGProyectoIPS.ClavePrimaria.Es Nulo
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.ClavePrimaria/esNulo.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.ClavePrimaria/esNulo.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue("false")]
		[global::System.ComponentModel.Browsable(false)]
		[global::System.ComponentModel.ReadOnly(true)]
		[DslModeling::DomainObjectId("a19f234c-cab5-4d2c-9207-74be191aa1df")]
		public global::System.String esNulo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return esNuloPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				esNuloPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the ClavePrimaria.esNulo domain property.
		/// </summary>
		internal sealed partial class esNuloPropertyHandler : DslModeling::DomainPropertyValueHandler<ClavePrimaria, global::System.String>
		{
			private esNuloPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the ClavePrimaria.esNulo domain property value handler.
			/// </summary>
			public static readonly esNuloPropertyHandler Instance = new esNuloPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the ClavePrimaria.esNulo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return esNuloDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(ClavePrimaria element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.esNuloPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(ClavePrimaria element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.esNuloPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Entidad opposite domain role accessor
		/// <summary>
		/// Gets or sets Entidad.
		/// Description for IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.ClavePrimaria
		/// </summary>
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.ClavePrimariaDomainRoleId) as Entidad;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.ClavePrimariaDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// DomainClass AtributoEntidad
	/// Description for IPS_GT16.XCXABGProyectoIPS.AtributoEntidad
	/// </summary>
	[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.AtributoEntidad.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.AtributoEntidad.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("b33d1352-091c-47ef-9177-7444f599df90")]
	public partial class AtributoEntidad : Atributo
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// AtributoEntidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xb33d1352, 0x091c, 0x47ef, 0x91, 0x77, 0x74, 0x44, 0xf5, 0x99, 0xdf, 0x90);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoEntidad(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoEntidad(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region esNulo domain property code
		
		/// <summary>
		/// esNulo domain property Id.
		/// </summary>
		public static readonly global::System.Guid esNuloDomainPropertyId = new global::System.Guid(0xd20ebc06, 0x928b, 0x4a35, 0xb9, 0xc9, 0xd4, 0xcb, 0xc3, 0xc1, 0xab, 0xa8);
		
		/// <summary>
		/// Storage for esNulo
		/// </summary>
		private global::System.Boolean esNuloPropertyStorage = true;
		
		/// <summary>
		/// Gets or sets the value of esNulo domain property.
		/// Description for IPS_GT16.XCXABGProyectoIPS.AtributoEntidad.Nullable
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.AtributoEntidad/esNulo.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.AtributoEntidad/esNulo.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue(true)]
		[DslModeling::DomainObjectId("d20ebc06-928b-4a35-b9c9-d4cbc3c1aba8")]
		public global::System.Boolean esNulo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return esNuloPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				esNuloPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the AtributoEntidad.esNulo domain property.
		/// </summary>
		internal sealed partial class esNuloPropertyHandler : DslModeling::DomainPropertyValueHandler<AtributoEntidad, global::System.Boolean>
		{
			private esNuloPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the AtributoEntidad.esNulo domain property value handler.
			/// </summary>
			public static readonly esNuloPropertyHandler Instance = new esNuloPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the AtributoEntidad.esNulo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return esNuloDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.Boolean GetValue(AtributoEntidad element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.esNuloPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(AtributoEntidad element, global::System.Boolean newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.Boolean oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.esNuloPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Entidad opposite domain role accessor
		/// <summary>
		/// Gets or sets Entidad.
		/// Description for
		/// IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad.AtributoEntidad
		/// </summary>
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId) as Entidad;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// DomainClass AtributoRelacion
	/// Description for IPS_GT16.XCXABGProyectoIPS.AtributoRelacion
	/// </summary>
	[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.AtributoRelacion.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.AtributoRelacion.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("04298733-d801-4b78-a7a8-595fa53a89e8")]
	public partial class AtributoRelacion : Atributo
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// AtributoRelacion domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x04298733, 0xd801, 0x4b78, 0xa7, 0xa8, 0x59, 0x5f, 0xa5, 0x3a, 0x89, 0xe8);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoRelacion(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoRelacion(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region esNulo domain property code
		
		/// <summary>
		/// esNulo domain property Id.
		/// </summary>
		public static readonly global::System.Guid esNuloDomainPropertyId = new global::System.Guid(0xc63eca4b, 0xe707, 0x4239, 0xb5, 0x1c, 0x7e, 0xeb, 0x11, 0x24, 0x7b, 0x50);
		
		/// <summary>
		/// Storage for esNulo
		/// </summary>
		private global::System.Boolean esNuloPropertyStorage = true;
		
		/// <summary>
		/// Gets or sets the value of esNulo domain property.
		/// Description for IPS_GT16.XCXABGProyectoIPS.AtributoRelacion.Nullable
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.AtributoRelacion/esNulo.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.AtributoRelacion/esNulo.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue(true)]
		[DslModeling::DomainObjectId("c63eca4b-e707-4239-b51c-7eeb11247b50")]
		public global::System.Boolean esNulo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return esNuloPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				esNuloPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the AtributoRelacion.esNulo domain property.
		/// </summary>
		internal sealed partial class esNuloPropertyHandler : DslModeling::DomainPropertyValueHandler<AtributoRelacion, global::System.Boolean>
		{
			private esNuloPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the AtributoRelacion.esNulo domain property value handler.
			/// </summary>
			public static readonly esNuloPropertyHandler Instance = new esNuloPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the AtributoRelacion.esNulo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return esNuloDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.Boolean GetValue(AtributoRelacion element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.esNuloPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(AtributoRelacion element, global::System.Boolean newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.Boolean oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.esNuloPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Relacion opposite domain role accessor
		/// <summary>
		/// Gets or sets Relacion.
		/// Description for
		/// IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion.AtributoRelacion
		/// </summary>
		public virtual Relacion Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion.AtributoRelacionDomainRoleId) as Relacion;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion.AtributoRelacionDomainRoleId, value);
			}
		}
		#endregion
	}
}
