//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// DomainRelationship TapizHasEntidad
	/// Description for IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad
	/// </summary>
	[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("0d15496c-ff9c-4b22-8438-8567a6efc936")]
	public partial class TapizHasEntidad : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// TapizHasEntidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x0d15496c, 0xff9c, 0x4b22, 0x84, 0x38, 0x85, 0x67, 0xa6, 0xef, 0xc9, 0x36);
	
				
		/// <summary>
		/// Constructor
		/// Creates a TapizHasEntidad link in the same Partition as the given Tapiz
		/// </summary>
		/// <param name="source">Tapiz to use as the source of the relationship.</param>
		/// <param name="target">Entidad to use as the target of the relationship.</param>
		public TapizHasEntidad(Tapiz source, Entidad target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(TapizHasEntidad.TapizDomainRoleId, source), new DslModeling::RoleAssignment(TapizHasEntidad.EntidadDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public TapizHasEntidad(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public TapizHasEntidad(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public TapizHasEntidad(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public TapizHasEntidad(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Tapiz domain role code
		
		/// <summary>
		/// Tapiz domain role Id.
		/// </summary>
		public static readonly global::System.Guid TapizDomainRoleId = new global::System.Guid(0x3c58ad50, 0xfebd, 0x432f, 0x97, 0x26, 0xe6, 0xb3, 0xe0, 0xe5, 0x79, 0x02);
		
		/// <summary>
		/// DomainRole Tapiz
		/// Description for IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad.Tapiz
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad/Tapiz.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad/Tapiz.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Entidad", PropertyDisplayNameKey="IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad/Tapiz.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("3c58ad50-febd-432f-9726-e6b3e0e57902")]
		public virtual Tapiz Tapiz
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Tapiz)DslModeling::DomainRoleInfo.GetRolePlayer(this, TapizDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, TapizDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Tapiz of a Entidad
		/// <summary>
		/// Gets Tapiz.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Tapiz GetTapiz(Entidad element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, EntidadDomainRoleId) as Tapiz;
		}
		
		/// <summary>
		/// Sets Tapiz.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetTapiz(Entidad element, Tapiz newTapiz)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, EntidadDomainRoleId, newTapiz);
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0x784bf662, 0x5ede, 0x4450, 0x93, 0x9e, 0xa5, 0x48, 0x50, 0x9e, 0xb3, 0x3b);
		
		/// <summary>
		/// DomainRole Entidad
		/// Description for IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad/Entidad.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad/Entidad.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Tapiz", PropertyDisplayNameKey="IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad/Entidad.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("784bf662-5ede-4450-939e-a548509eb33b")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a Tapiz
		/// <summary>
		/// Gets a list of Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Entidad> GetEntidad(Tapiz element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(element, TapizDomainRoleId);
		}
		#endregion
		#region Tapiz link accessor
		/// <summary>
		/// Get the list of TapizHasEntidad links to a Tapiz.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad> GetLinksToEntidad ( global::IPS_GT16.XCXABGProyectoIPS.Tapiz tapizInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad>(tapizInstance, global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad.TapizDomainRoleId);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the TapizHasEntidad link to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad GetLinkToTapiz (global::IPS_GT16.XCXABGProyectoIPS.Entidad entidadInstance)
		{
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad>(entidadInstance, global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad.EntidadDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Entidad not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region TapizHasEntidad instance accessors
		
		/// <summary>
		/// Get any TapizHasEntidad links between a given Tapiz and a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad> GetLinks( global::IPS_GT16.XCXABGProyectoIPS.Tapiz source, global::IPS_GT16.XCXABGProyectoIPS.Entidad target )
		{
			global::System.Collections.Generic.List<global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad> outLinks = new global::System.Collections.Generic.List<global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad>();
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad>(source, global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad.TapizDomainRoleId);
			foreach ( global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad link in links )
			{
				if ( target.Equals(link.Entidad) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one TapizHasEntidad link between a given Tapizand a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad GetLink( global::IPS_GT16.XCXABGProyectoIPS.Tapiz source, global::IPS_GT16.XCXABGProyectoIPS.Entidad target )
		{
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad>(source, global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad.TapizDomainRoleId);
			foreach ( global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad link in links )
			{
				if ( target.Equals(link.Entidad) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// DomainRelationship EntidadReferencesRelacioned
	/// Description for IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned
	/// </summary>
	[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship()]
	[DslModeling::DomainObjectId("28eeb5f9-f783-4041-8597-4fe968276418")]
	public partial class EntidadReferencesRelacioned : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EntidadReferencesRelacioned domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x28eeb5f9, 0xf783, 0x4041, 0x85, 0x97, 0x4f, 0xe9, 0x68, 0x27, 0x64, 0x18);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EntidadReferencesRelacioned link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">Relacion to use as the target of the relationship.</param>
		public EntidadReferencesRelacioned(Entidad source, Relacion target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EntidadReferencesRelacioned.EntidadDomainRoleId, source), new DslModeling::RoleAssignment(EntidadReferencesRelacioned.RelacionDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadReferencesRelacioned(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadReferencesRelacioned(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadReferencesRelacioned(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadReferencesRelacioned(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0x8e66c8bb, 0x48c8, 0x406d, 0x8c, 0xee, 0x5e, 0xe2, 0xb4, 0x97, 0x93, 0xbb);
		
		/// <summary>
		/// DomainRole Entidad
		/// Description for IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned/Entidad.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned/Entidad.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Relacioned", PropertyDisplayNameKey="IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned/Entidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.OneMany)]
		[DslModeling::DomainObjectId("8e66c8bb-48c8-406d-8cee-5ee2b49793bb")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a Relacion
		/// <summary>
		/// Gets a list of Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Entidad> GetEntidad(Relacion element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(element, RelacionDomainRoleId);
		}
		#endregion
		#region Relacion domain role code
		
		/// <summary>
		/// Relacion domain role Id.
		/// </summary>
		public static readonly global::System.Guid RelacionDomainRoleId = new global::System.Guid(0x917172bb, 0x150e, 0x4796, 0xb6, 0xff, 0x9d, 0x81, 0x0a, 0xd9, 0xba, 0xd6);
		
		/// <summary>
		/// DomainRole Relacion
		/// Description for IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned.Relacion
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned/Relacion.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned/Relacion.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Entidad", PropertyDisplayNameKey="IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned/Relacion.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.OneMany)]
		[DslModeling::DomainObjectId("917172bb-150e-4796-b6ff-9d810ad9bad6")]
		public virtual Relacion Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Relacion)DslModeling::DomainRoleInfo.GetRolePlayer(this, RelacionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, RelacionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Relacioned of a Entidad
		/// <summary>
		/// Gets a list of Relacioned.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Relacion> GetRelacioned(Entidad element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(element, EntidadDomainRoleId);
		}
		#endregion
		#region aCardMin domain property code
		
		/// <summary>
		/// aCardMin domain property Id.
		/// </summary>
		public static readonly global::System.Guid aCardMinDomainPropertyId = new global::System.Guid(0x1a73bd08, 0xec98, 0x4d06, 0xab, 0xe2, 0x5c, 0x8f, 0xc5, 0x3c, 0x15, 0xb4);
		
		/// <summary>
		/// Storage for aCardMin
		/// </summary>
		private cardinalidad aCardMinPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of aCardMin domain property.
		/// Description for IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned.ACard Min
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned/aCardMin.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned/aCardMin.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("1a73bd08-ec98-4d06-abe2-5c8fc53c15b4")]
		public cardinalidad aCardMin
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return aCardMinPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				aCardMinPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the EntidadReferencesRelacioned.aCardMin domain property.
		/// </summary>
		internal sealed partial class aCardMinPropertyHandler : DslModeling::DomainPropertyValueHandler<EntidadReferencesRelacioned, cardinalidad>
		{
			private aCardMinPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the EntidadReferencesRelacioned.aCardMin domain property value handler.
			/// </summary>
			public static readonly aCardMinPropertyHandler Instance = new aCardMinPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the EntidadReferencesRelacioned.aCardMin domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return aCardMinDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed cardinalidad GetValue(EntidadReferencesRelacioned element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.aCardMinPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(EntidadReferencesRelacioned element, cardinalidad newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				cardinalidad oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.aCardMinPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region bCardMax domain property code
		
		/// <summary>
		/// bCardMax domain property Id.
		/// </summary>
		public static readonly global::System.Guid bCardMaxDomainPropertyId = new global::System.Guid(0x986bf74e, 0xf1db, 0x4487, 0x88, 0xf2, 0x3e, 0xee, 0x41, 0x1f, 0x6a, 0xd9);
		
		/// <summary>
		/// Storage for bCardMax
		/// </summary>
		private cardinalidad bCardMaxPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of bCardMax domain property.
		/// Description for IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned.BCard Max
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned/bCardMax.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned/bCardMax.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("986bf74e-f1db-4487-88f2-3eee411f6ad9")]
		public cardinalidad bCardMax
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return bCardMaxPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				bCardMaxPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the EntidadReferencesRelacioned.bCardMax domain property.
		/// </summary>
		internal sealed partial class bCardMaxPropertyHandler : DslModeling::DomainPropertyValueHandler<EntidadReferencesRelacioned, cardinalidad>
		{
			private bCardMaxPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the EntidadReferencesRelacioned.bCardMax domain property value handler.
			/// </summary>
			public static readonly bCardMaxPropertyHandler Instance = new bCardMaxPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the EntidadReferencesRelacioned.bCardMax domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return bCardMaxDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed cardinalidad GetValue(EntidadReferencesRelacioned element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.bCardMaxPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(EntidadReferencesRelacioned element, cardinalidad newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				cardinalidad oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.bCardMaxPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the list of EntidadReferencesRelacioned links to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned> GetLinksToRelacioned ( global::IPS_GT16.XCXABGProyectoIPS.Entidad entidadInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned>(entidadInstance, global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned.EntidadDomainRoleId);
		}
		#endregion
		#region Relacion link accessor
		/// <summary>
		/// Get the list of EntidadReferencesRelacioned links to a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned> GetLinksToEntidad ( global::IPS_GT16.XCXABGProyectoIPS.Relacion relacionInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned>(relacionInstance, global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned.RelacionDomainRoleId);
		}
		#endregion
		#region EntidadReferencesRelacioned instance accessors
		
		/// <summary>
		/// Get any EntidadReferencesRelacioned links between a given Entidad and a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned> GetLinks( global::IPS_GT16.XCXABGProyectoIPS.Entidad source, global::IPS_GT16.XCXABGProyectoIPS.Relacion target )
		{
			global::System.Collections.Generic.List<global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned> outLinks = new global::System.Collections.Generic.List<global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned>();
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned>(source, global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned.EntidadDomainRoleId);
			foreach ( global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EntidadReferencesRelacioned link between a given Entidadand a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned GetLink( global::IPS_GT16.XCXABGProyectoIPS.Entidad source, global::IPS_GT16.XCXABGProyectoIPS.Relacion target )
		{
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned>(source, global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned.EntidadDomainRoleId);
			foreach ( global::IPS_GT16.XCXABGProyectoIPS.EntidadReferencesRelacioned link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// DomainRelationship TapizHasRelacioned
	/// Description for IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned
	/// </summary>
	[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("0f44fa22-fdcc-4fa2-ac21-dd282bcd6f43")]
	public partial class TapizHasRelacioned : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// TapizHasRelacioned domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x0f44fa22, 0xfdcc, 0x4fa2, 0xac, 0x21, 0xdd, 0x28, 0x2b, 0xcd, 0x6f, 0x43);
	
				
		/// <summary>
		/// Constructor
		/// Creates a TapizHasRelacioned link in the same Partition as the given Tapiz
		/// </summary>
		/// <param name="source">Tapiz to use as the source of the relationship.</param>
		/// <param name="target">Relacion to use as the target of the relationship.</param>
		public TapizHasRelacioned(Tapiz source, Relacion target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(TapizHasRelacioned.TapizDomainRoleId, source), new DslModeling::RoleAssignment(TapizHasRelacioned.RelacionDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public TapizHasRelacioned(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public TapizHasRelacioned(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public TapizHasRelacioned(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public TapizHasRelacioned(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Tapiz domain role code
		
		/// <summary>
		/// Tapiz domain role Id.
		/// </summary>
		public static readonly global::System.Guid TapizDomainRoleId = new global::System.Guid(0x2e655d14, 0x9690, 0x444d, 0x82, 0xa5, 0x6d, 0x42, 0x18, 0xd4, 0xb2, 0x4b);
		
		/// <summary>
		/// DomainRole Tapiz
		/// Description for IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned.Tapiz
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned/Tapiz.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned/Tapiz.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Relacioned", PropertyDisplayNameKey="IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned/Tapiz.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("2e655d14-9690-444d-82a5-6d4218d4b24b")]
		public virtual Tapiz Tapiz
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Tapiz)DslModeling::DomainRoleInfo.GetRolePlayer(this, TapizDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, TapizDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Tapiz of a Relacion
		/// <summary>
		/// Gets Tapiz.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Tapiz GetTapiz(Relacion element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, RelacionDomainRoleId) as Tapiz;
		}
		
		/// <summary>
		/// Sets Tapiz.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetTapiz(Relacion element, Tapiz newTapiz)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, RelacionDomainRoleId, newTapiz);
		}
		#endregion
		#region Relacion domain role code
		
		/// <summary>
		/// Relacion domain role Id.
		/// </summary>
		public static readonly global::System.Guid RelacionDomainRoleId = new global::System.Guid(0xd2e09dc2, 0x4d71, 0x45a6, 0x80, 0x84, 0x9f, 0x8a, 0x9a, 0x75, 0x11, 0xa9);
		
		/// <summary>
		/// DomainRole Relacion
		/// Description for IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned.Relacion
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned/Relacion.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned/Relacion.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Tapiz", PropertyDisplayNameKey="IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned/Relacion.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("d2e09dc2-4d71-45a6-8084-9f8a9a7511a9")]
		public virtual Relacion Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Relacion)DslModeling::DomainRoleInfo.GetRolePlayer(this, RelacionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, RelacionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Relacioned of a Tapiz
		/// <summary>
		/// Gets a list of Relacioned.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Relacion> GetRelacioned(Tapiz element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(element, TapizDomainRoleId);
		}
		#endregion
		#region Tapiz link accessor
		/// <summary>
		/// Get the list of TapizHasRelacioned links to a Tapiz.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned> GetLinksToRelacioned ( global::IPS_GT16.XCXABGProyectoIPS.Tapiz tapizInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned>(tapizInstance, global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned.TapizDomainRoleId);
		}
		#endregion
		#region Relacion link accessor
		/// <summary>
		/// Get the TapizHasRelacioned link to a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned GetLinkToTapiz (global::IPS_GT16.XCXABGProyectoIPS.Relacion relacionInstance)
		{
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned>(relacionInstance, global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned.RelacionDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Relacion not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region TapizHasRelacioned instance accessors
		
		/// <summary>
		/// Get any TapizHasRelacioned links between a given Tapiz and a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned> GetLinks( global::IPS_GT16.XCXABGProyectoIPS.Tapiz source, global::IPS_GT16.XCXABGProyectoIPS.Relacion target )
		{
			global::System.Collections.Generic.List<global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned> outLinks = new global::System.Collections.Generic.List<global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned>();
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned>(source, global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned.TapizDomainRoleId);
			foreach ( global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one TapizHasRelacioned link between a given Tapizand a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned GetLink( global::IPS_GT16.XCXABGProyectoIPS.Tapiz source, global::IPS_GT16.XCXABGProyectoIPS.Relacion target )
		{
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned>(source, global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned.TapizDomainRoleId);
			foreach ( global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// DomainRelationship EntidadHasClavePrimaria
	/// Description for IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria
	/// </summary>
	[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("eb8d8fc2-5eef-4c3c-bb06-4663d61f34d7")]
	public partial class EntidadHasClavePrimaria : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EntidadHasClavePrimaria domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xeb8d8fc2, 0x5eef, 0x4c3c, 0xbb, 0x06, 0x46, 0x63, 0xd6, 0x1f, 0x34, 0xd7);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EntidadHasClavePrimaria link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">ClavePrimaria to use as the target of the relationship.</param>
		public EntidadHasClavePrimaria(Entidad source, ClavePrimaria target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EntidadHasClavePrimaria.EntidadDomainRoleId, source), new DslModeling::RoleAssignment(EntidadHasClavePrimaria.ClavePrimariaDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadHasClavePrimaria(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadHasClavePrimaria(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadHasClavePrimaria(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadHasClavePrimaria(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0x10a6f6d0, 0x0cd7, 0x4963, 0xb2, 0x3a, 0x20, 0xf1, 0xd4, 0x14, 0x34, 0x07);
		
		/// <summary>
		/// DomainRole Entidad
		/// Description for IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria/Entidad.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria/Entidad.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "ClavePrimaria", PropertyDisplayNameKey="IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria/Entidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("10a6f6d0-0cd7-4963-b23a-20f1d4143407")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a ClavePrimaria
		/// <summary>
		/// Gets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Entidad GetEntidad(ClavePrimaria element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, ClavePrimariaDomainRoleId) as Entidad;
		}
		
		/// <summary>
		/// Sets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetEntidad(ClavePrimaria element, Entidad newEntidad)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, ClavePrimariaDomainRoleId, newEntidad);
		}
		#endregion
		#region ClavePrimaria domain role code
		
		/// <summary>
		/// ClavePrimaria domain role Id.
		/// </summary>
		public static readonly global::System.Guid ClavePrimariaDomainRoleId = new global::System.Guid(0x0758825e, 0x7b39, 0x47e5, 0x81, 0x51, 0x9d, 0x5a, 0xd0, 0x5b, 0x81, 0x9a);
		
		/// <summary>
		/// DomainRole ClavePrimaria
		/// Description for IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.ClavePrimaria
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria/ClavePrimaria.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria/ClavePrimaria.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Entidad", PropertyDisplayNameKey="IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria/ClavePrimaria.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("0758825e-7b39-47e5-8151-9d5ad05b819a")]
		public virtual ClavePrimaria ClavePrimaria
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (ClavePrimaria)DslModeling::DomainRoleInfo.GetRolePlayer(this, ClavePrimariaDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ClavePrimariaDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access ClavePrimaria of a Entidad
		/// <summary>
		/// Gets ClavePrimaria.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static ClavePrimaria GetClavePrimaria(Entidad element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, EntidadDomainRoleId) as ClavePrimaria;
		}
		
		/// <summary>
		/// Sets ClavePrimaria.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetClavePrimaria(Entidad element, ClavePrimaria newClavePrimaria)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, EntidadDomainRoleId, newClavePrimaria);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the EntidadHasClavePrimaria link to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria GetLinkToClavePrimaria (global::IPS_GT16.XCXABGProyectoIPS.Entidad entidadInstance)
		{
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria>(entidadInstance, global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.EntidadDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Entidad not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region ClavePrimaria link accessor
		/// <summary>
		/// Get the EntidadHasClavePrimaria link to a ClavePrimaria.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria GetLinkToEntidad (global::IPS_GT16.XCXABGProyectoIPS.ClavePrimaria clavePrimariaInstance)
		{
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria>(clavePrimariaInstance, global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.ClavePrimariaDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of ClavePrimaria not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region EntidadHasClavePrimaria instance accessors
		
		/// <summary>
		/// Get any EntidadHasClavePrimaria links between a given Entidad and a ClavePrimaria.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria> GetLinks( global::IPS_GT16.XCXABGProyectoIPS.Entidad source, global::IPS_GT16.XCXABGProyectoIPS.ClavePrimaria target )
		{
			global::System.Collections.Generic.List<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria> outLinks = new global::System.Collections.Generic.List<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria>();
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria>(source, global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.EntidadDomainRoleId);
			foreach ( global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria link in links )
			{
				if ( target.Equals(link.ClavePrimaria) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EntidadHasClavePrimaria link between a given Entidadand a ClavePrimaria.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria GetLink( global::IPS_GT16.XCXABGProyectoIPS.Entidad source, global::IPS_GT16.XCXABGProyectoIPS.ClavePrimaria target )
		{
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria>(source, global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.EntidadDomainRoleId);
			foreach ( global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria link in links )
			{
				if ( target.Equals(link.ClavePrimaria) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// DomainRelationship RelacionHasAtributoRelacion
	/// Description for IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion
	/// </summary>
	[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("f9b59c51-8a2a-4768-9a9e-29ef6654db4a")]
	public partial class RelacionHasAtributoRelacion : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// RelacionHasAtributoRelacion domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xf9b59c51, 0x8a2a, 0x4768, 0x9a, 0x9e, 0x29, 0xef, 0x66, 0x54, 0xdb, 0x4a);
	
				
		/// <summary>
		/// Constructor
		/// Creates a RelacionHasAtributoRelacion link in the same Partition as the given Relacion
		/// </summary>
		/// <param name="source">Relacion to use as the source of the relationship.</param>
		/// <param name="target">AtributoRelacion to use as the target of the relationship.</param>
		public RelacionHasAtributoRelacion(Relacion source, AtributoRelacion target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(RelacionHasAtributoRelacion.RelacionDomainRoleId, source), new DslModeling::RoleAssignment(RelacionHasAtributoRelacion.AtributoRelacionDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public RelacionHasAtributoRelacion(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public RelacionHasAtributoRelacion(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public RelacionHasAtributoRelacion(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public RelacionHasAtributoRelacion(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Relacion domain role code
		
		/// <summary>
		/// Relacion domain role Id.
		/// </summary>
		public static readonly global::System.Guid RelacionDomainRoleId = new global::System.Guid(0x40bf4528, 0x4c8f, 0x4313, 0x98, 0x16, 0x11, 0x15, 0x44, 0xaf, 0xa2, 0x75);
		
		/// <summary>
		/// DomainRole Relacion
		/// Description for IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion.Relacion
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion/Relacion.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion/Relacion.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "AtributoRelacion", PropertyDisplayNameKey="IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion/Relacion.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("40bf4528-4c8f-4313-9816-111544afa275")]
		public virtual Relacion Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Relacion)DslModeling::DomainRoleInfo.GetRolePlayer(this, RelacionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, RelacionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Relacion of a AtributoRelacion
		/// <summary>
		/// Gets Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Relacion GetRelacion(AtributoRelacion element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, AtributoRelacionDomainRoleId) as Relacion;
		}
		
		/// <summary>
		/// Sets Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetRelacion(AtributoRelacion element, Relacion newRelacion)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, AtributoRelacionDomainRoleId, newRelacion);
		}
		#endregion
		#region AtributoRelacion domain role code
		
		/// <summary>
		/// AtributoRelacion domain role Id.
		/// </summary>
		public static readonly global::System.Guid AtributoRelacionDomainRoleId = new global::System.Guid(0x16280dfa, 0xae19, 0x43d6, 0x90, 0xb7, 0x76, 0xf6, 0x74, 0x0b, 0x84, 0x4f);
		
		/// <summary>
		/// DomainRole AtributoRelacion
		/// Description for
		/// IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion.AtributoRelacion
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion/AtributoRelacion.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion/AtributoRelacion.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Relacion", PropertyDisplayNameKey="IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion/AtributoRelacion.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("16280dfa-ae19-43d6-90b7-76f6740b844f")]
		public virtual AtributoRelacion AtributoRelacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (AtributoRelacion)DslModeling::DomainRoleInfo.GetRolePlayer(this, AtributoRelacionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, AtributoRelacionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access AtributoRelacion of a Relacion
		/// <summary>
		/// Gets a list of AtributoRelacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<AtributoRelacion> GetAtributoRelacion(Relacion element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoRelacion>, AtributoRelacion>(element, RelacionDomainRoleId);
		}
		#endregion
		#region Relacion link accessor
		/// <summary>
		/// Get the list of RelacionHasAtributoRelacion links to a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion> GetLinksToAtributoRelacion ( global::IPS_GT16.XCXABGProyectoIPS.Relacion relacionInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion>(relacionInstance, global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion.RelacionDomainRoleId);
		}
		#endregion
		#region AtributoRelacion link accessor
		/// <summary>
		/// Get the RelacionHasAtributoRelacion link to a AtributoRelacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion GetLinkToRelacion (global::IPS_GT16.XCXABGProyectoIPS.AtributoRelacion atributoRelacionInstance)
		{
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion>(atributoRelacionInstance, global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion.AtributoRelacionDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of AtributoRelacion not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region RelacionHasAtributoRelacion instance accessors
		
		/// <summary>
		/// Get any RelacionHasAtributoRelacion links between a given Relacion and a AtributoRelacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion> GetLinks( global::IPS_GT16.XCXABGProyectoIPS.Relacion source, global::IPS_GT16.XCXABGProyectoIPS.AtributoRelacion target )
		{
			global::System.Collections.Generic.List<global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion> outLinks = new global::System.Collections.Generic.List<global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion>();
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion>(source, global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion.RelacionDomainRoleId);
			foreach ( global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion link in links )
			{
				if ( target.Equals(link.AtributoRelacion) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one RelacionHasAtributoRelacion link between a given Relacionand a AtributoRelacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion GetLink( global::IPS_GT16.XCXABGProyectoIPS.Relacion source, global::IPS_GT16.XCXABGProyectoIPS.AtributoRelacion target )
		{
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion>(source, global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion.RelacionDomainRoleId);
			foreach ( global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion link in links )
			{
				if ( target.Equals(link.AtributoRelacion) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// DomainRelationship EntidadHasAtributoEntidad
	/// Description for IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad
	/// </summary>
	[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("780d890a-d9da-42b4-82d8-2029b67a94d1")]
	public partial class EntidadHasAtributoEntidad : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EntidadHasAtributoEntidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x780d890a, 0xd9da, 0x42b4, 0x82, 0xd8, 0x20, 0x29, 0xb6, 0x7a, 0x94, 0xd1);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EntidadHasAtributoEntidad link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">AtributoEntidad to use as the target of the relationship.</param>
		public EntidadHasAtributoEntidad(Entidad source, AtributoEntidad target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EntidadHasAtributoEntidad.EntidadDomainRoleId, source), new DslModeling::RoleAssignment(EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadHasAtributoEntidad(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadHasAtributoEntidad(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadHasAtributoEntidad(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadHasAtributoEntidad(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0xc870a57c, 0xc2e2, 0x4444, 0xb4, 0xd1, 0xcc, 0x9a, 0x70, 0xe9, 0x1b, 0xfa);
		
		/// <summary>
		/// DomainRole Entidad
		/// Description for IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad/Entidad.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad/Entidad.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "AtributoEntidad", PropertyDisplayNameKey="IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad/Entidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("c870a57c-c2e2-4444-b4d1-cc9a70e91bfa")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a AtributoEntidad
		/// <summary>
		/// Gets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Entidad GetEntidad(AtributoEntidad element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, AtributoEntidadDomainRoleId) as Entidad;
		}
		
		/// <summary>
		/// Sets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetEntidad(AtributoEntidad element, Entidad newEntidad)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, AtributoEntidadDomainRoleId, newEntidad);
		}
		#endregion
		#region AtributoEntidad domain role code
		
		/// <summary>
		/// AtributoEntidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid AtributoEntidadDomainRoleId = new global::System.Guid(0x49dc6510, 0xa270, 0x4855, 0xb9, 0x66, 0xd9, 0x61, 0xc4, 0x6e, 0xdd, 0x4d);
		
		/// <summary>
		/// DomainRole AtributoEntidad
		/// Description for
		/// IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad.AtributoEntidad
		/// </summary>
		[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad/AtributoEntidad.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad/AtributoEntidad.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Entidad", PropertyDisplayNameKey="IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad/AtributoEntidad.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("49dc6510-a270-4855-b966-d961c46edd4d")]
		public virtual AtributoEntidad AtributoEntidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (AtributoEntidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, AtributoEntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, AtributoEntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access AtributoEntidad of a Entidad
		/// <summary>
		/// Gets a list of AtributoEntidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<AtributoEntidad> GetAtributoEntidad(Entidad element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoEntidad>, AtributoEntidad>(element, EntidadDomainRoleId);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the list of EntidadHasAtributoEntidad links to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad> GetLinksToAtributoEntidad ( global::IPS_GT16.XCXABGProyectoIPS.Entidad entidadInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad>(entidadInstance, global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad.EntidadDomainRoleId);
		}
		#endregion
		#region AtributoEntidad link accessor
		/// <summary>
		/// Get the EntidadHasAtributoEntidad link to a AtributoEntidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad GetLinkToEntidad (global::IPS_GT16.XCXABGProyectoIPS.AtributoEntidad atributoEntidadInstance)
		{
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad>(atributoEntidadInstance, global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of AtributoEntidad not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region EntidadHasAtributoEntidad instance accessors
		
		/// <summary>
		/// Get any EntidadHasAtributoEntidad links between a given Entidad and a AtributoEntidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad> GetLinks( global::IPS_GT16.XCXABGProyectoIPS.Entidad source, global::IPS_GT16.XCXABGProyectoIPS.AtributoEntidad target )
		{
			global::System.Collections.Generic.List<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad> outLinks = new global::System.Collections.Generic.List<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad>();
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad>(source, global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad.EntidadDomainRoleId);
			foreach ( global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad link in links )
			{
				if ( target.Equals(link.AtributoEntidad) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EntidadHasAtributoEntidad link between a given Entidadand a AtributoEntidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad GetLink( global::IPS_GT16.XCXABGProyectoIPS.Entidad source, global::IPS_GT16.XCXABGProyectoIPS.AtributoEntidad target )
		{
			global::System.Collections.Generic.IList<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad>(source, global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad.EntidadDomainRoleId);
			foreach ( global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad link in links )
			{
				if ( target.Equals(link.AtributoEntidad) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
