//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// DomainModel XCXABGProyectoIPSDomainModel
	/// Description for IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPS
	/// </summary>
	[DslDesign::DisplayNameResource("IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel.DisplayName", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("5289e232-b9f1-4684-ac29-f2cb3ddf5dbf")]
	public partial class XCXABGProyectoIPSDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// XCXABGProyectoIPSDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x5289e232, 0xb9f1, 0x4684, 0xac, 0x29, 0xf2, 0xcb, 0x3d, 0xdf, 0x5d, 0xbf);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public XCXABGProyectoIPSDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(Tapiz),
				typeof(Entidad),
				typeof(Relacion),
				typeof(Atributo),
				typeof(ClavePrimaria),
				typeof(AtributoEntidad),
				typeof(AtributoRelacion),
				typeof(TapizHasEntidad),
				typeof(EntidadReferencesRelacioned),
				typeof(TapizHasRelacioned),
				typeof(EntidadHasClavePrimaria),
				typeof(RelacionHasAtributoRelacion),
				typeof(EntidadHasAtributoEntidad),
				typeof(XCXABGProyectoIPSDiagram),
				typeof(EntidadRelacion),
				typeof(EntidadGS),
				typeof(RelacionGS),
				typeof(AtributoRelacionGS),
				typeof(AtributoEntidadGS),
				typeof(ClavePrimariaGS),
				typeof(global::IPS_GT16.XCXABGProyectoIPS.FixUpDiagram),
				typeof(global::IPS_GT16.XCXABGProyectoIPS.DecoratorPropertyChanged),
				typeof(global::IPS_GT16.XCXABGProyectoIPS.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Entidad), "Name", Entidad.NameDomainPropertyId, typeof(Entidad.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Relacion), "Name", Relacion.NameDomainPropertyId, typeof(Relacion.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "Nombre", Atributo.NombreDomainPropertyId, typeof(Atributo.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "LongitudDato", Atributo.LongitudDatoDomainPropertyId, typeof(Atributo.LongitudDatoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "NameTipo", Atributo.NameTipoDomainPropertyId, typeof(Atributo.NameTipoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "TipoDato", Atributo.TipoDatoDomainPropertyId, typeof(Atributo.TipoDatoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "letraSize", Atributo.letraSizeDomainPropertyId, typeof(Atributo.letraSizePropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "colorLetra", Atributo.colorLetraDomainPropertyId, typeof(Atributo.colorLetraPropertyHandler)),
				new DomainMemberInfo(typeof(ClavePrimaria), "esNulo", ClavePrimaria.esNuloDomainPropertyId, typeof(ClavePrimaria.esNuloPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoEntidad), "esNulo", AtributoEntidad.esNuloDomainPropertyId, typeof(AtributoEntidad.esNuloPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoRelacion), "esNulo", AtributoRelacion.esNuloDomainPropertyId, typeof(AtributoRelacion.esNuloPropertyHandler)),
				new DomainMemberInfo(typeof(EntidadReferencesRelacioned), "aCardMin", EntidadReferencesRelacioned.aCardMinDomainPropertyId, typeof(EntidadReferencesRelacioned.aCardMinPropertyHandler)),
				new DomainMemberInfo(typeof(EntidadReferencesRelacioned), "bCardMax", EntidadReferencesRelacioned.bCardMaxDomainPropertyId, typeof(EntidadReferencesRelacioned.bCardMaxPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(TapizHasEntidad), "Tapiz", TapizHasEntidad.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasEntidad), "Entidad", TapizHasEntidad.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesRelacioned), "Entidad", EntidadReferencesRelacioned.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesRelacioned), "Relacion", EntidadReferencesRelacioned.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasRelacioned), "Tapiz", TapizHasRelacioned.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasRelacioned), "Relacion", TapizHasRelacioned.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasClavePrimaria), "Entidad", EntidadHasClavePrimaria.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasClavePrimaria), "ClavePrimaria", EntidadHasClavePrimaria.ClavePrimariaDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionHasAtributoRelacion), "Relacion", RelacionHasAtributoRelacion.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionHasAtributoRelacion), "AtributoRelacion", RelacionHasAtributoRelacion.AtributoRelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasAtributoEntidad), "Entidad", EntidadHasAtributoEntidad.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasAtributoEntidad), "AtributoEntidad", EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(14);
				createElementMap.Add(typeof(Tapiz), 0);
				createElementMap.Add(typeof(Entidad), 1);
				createElementMap.Add(typeof(Relacion), 2);
				createElementMap.Add(typeof(Atributo), 3);
				createElementMap.Add(typeof(ClavePrimaria), 4);
				createElementMap.Add(typeof(AtributoEntidad), 5);
				createElementMap.Add(typeof(AtributoRelacion), 6);
				createElementMap.Add(typeof(XCXABGProyectoIPSDiagram), 7);
				createElementMap.Add(typeof(EntidadRelacion), 8);
				createElementMap.Add(typeof(EntidadGS), 9);
				createElementMap.Add(typeof(RelacionGS), 10);
				createElementMap.Add(typeof(AtributoRelacionGS), 11);
				createElementMap.Add(typeof(AtributoEntidadGS), 12);
				createElementMap.Add(typeof(ClavePrimariaGS), 13);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new Tapiz(partition, propertyAssignments);
				case 1: return new Entidad(partition, propertyAssignments);
				case 2: return new Relacion(partition, propertyAssignments);
				case 3: return new Atributo(partition, propertyAssignments);
				case 4: return new ClavePrimaria(partition, propertyAssignments);
				case 5: return new AtributoEntidad(partition, propertyAssignments);
				case 6: return new AtributoRelacion(partition, propertyAssignments);
				case 7: return new XCXABGProyectoIPSDiagram(partition, propertyAssignments);
				case 8: return new EntidadRelacion(partition, propertyAssignments);
				case 9: return new EntidadGS(partition, propertyAssignments);
				case 10: return new RelacionGS(partition, propertyAssignments);
				case 11: return new AtributoRelacionGS(partition, propertyAssignments);
				case 12: return new AtributoEntidadGS(partition, propertyAssignments);
				case 13: return new ClavePrimariaGS(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(6);
				createElementLinkMap.Add(typeof(TapizHasEntidad), 0);
				createElementLinkMap.Add(typeof(EntidadReferencesRelacioned), 1);
				createElementLinkMap.Add(typeof(TapizHasRelacioned), 2);
				createElementLinkMap.Add(typeof(EntidadHasClavePrimaria), 3);
				createElementLinkMap.Add(typeof(RelacionHasAtributoRelacion), 4);
				createElementLinkMap.Add(typeof(EntidadHasAtributoEntidad), 5);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new TapizHasEntidad(partition, roleAssignments, propertyAssignments);
				case 1: return new EntidadReferencesRelacioned(partition, roleAssignments, propertyAssignments);
				case 2: return new TapizHasRelacioned(partition, roleAssignments, propertyAssignments);
				case 3: return new EntidadHasClavePrimaria(partition, roleAssignments, propertyAssignments);
				case 4: return new RelacionHasAtributoRelacion(partition, roleAssignments, propertyAssignments);
				case 5: return new EntidadHasAtributoEntidad(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return XCXABGProyectoIPSDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (XCXABGProyectoIPSDomainModel.resourceManager == null)
				{
					XCXABGProyectoIPSDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(XCXABGProyectoIPSDomainModel).Assembly);
				}
				return XCXABGProyectoIPSDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return XCXABGProyectoIPSDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return XCXABGProyectoIPSDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (XCXABGProyectoIPSDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new XCXABGProyectoIPSCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					XCXABGProyectoIPSDomainModel.copyClosure = copyFilter;
				}
				return XCXABGProyectoIPSDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (XCXABGProyectoIPSDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new XCXABGProyectoIPSDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					XCXABGProyectoIPSDomainModel.removeClosure = removeFilter;
				}
				return XCXABGProyectoIPSDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::IPS_GT16.XCXABGProyectoIPS.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::IPS_GT16.XCXABGProyectoIPS.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::IPS_GT16.XCXABGProyectoIPS.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::IPS_GT16.XCXABGProyectoIPS.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::IPS_GT16.XCXABGProyectoIPS.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::IPS_GT16.XCXABGProyectoIPS.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class XCXABGProyectoIPSDeleteClosure : XCXABGProyectoIPSDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public XCXABGProyectoIPSDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class XCXABGProyectoIPSDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public XCXABGProyectoIPSDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::IPS_GT16.XCXABGProyectoIPS.TapizHasEntidad.EntidadDomainRoleId, true);
			DomainRoles.Add(global::IPS_GT16.XCXABGProyectoIPS.TapizHasRelacioned.RelacionDomainRoleId, true);
			DomainRoles.Add(global::IPS_GT16.XCXABGProyectoIPS.EntidadHasClavePrimaria.ClavePrimariaDomainRoleId, true);
			DomainRoles.Add(global::IPS_GT16.XCXABGProyectoIPS.RelacionHasAtributoRelacion.AtributoRelacionDomainRoleId, true);
			DomainRoles.Add(global::IPS_GT16.XCXABGProyectoIPS.EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class XCXABGProyectoIPSCopyClosure : XCXABGProyectoIPSCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public XCXABGProyectoIPSCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class XCXABGProyectoIPSCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public XCXABGProyectoIPSCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: datos
	/// Description for IPS_GT16.XCXABGProyectoIPS.datos
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum datos
	{
		/// <summary>
		/// entero
		/// Description for IPS_GT16.XCXABGProyectoIPS.datos.entero
		/// </summary>
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.datos/entero.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		entero = 0,
		/// <summary>
		/// real
		/// Description for IPS_GT16.XCXABGProyectoIPS.datos.real
		/// </summary>
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.datos/real.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		real = 1,
		/// <summary>
		/// fecha
		/// Description for IPS_GT16.XCXABGProyectoIPS.datos.fecha
		/// </summary>
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.datos/fecha.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		fecha = 2,
		/// <summary>
		/// alfanumerico
		/// Description for IPS_GT16.XCXABGProyectoIPS.datos.alfanumerico
		/// </summary>
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.datos/alfanumerico.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		alfanumerico = 3,
	}
}
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: cardinalidad
	/// Description for IPS_GT16.XCXABGProyectoIPS.cardinalidad
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum cardinalidad
	{
		/// <summary>
		/// cero
		/// Description for IPS_GT16.XCXABGProyectoIPS.cardinalidad.cero
		/// </summary>
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.cardinalidad/cero.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		cero = 0,
		/// <summary>
		/// uno
		/// Description for IPS_GT16.XCXABGProyectoIPS.cardinalidad.uno
		/// </summary>
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.cardinalidad/uno.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		uno = 1,
		/// <summary>
		/// dos
		/// Description for IPS_GT16.XCXABGProyectoIPS.cardinalidad.dos
		/// </summary>
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.cardinalidad/dos.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		dos = 2,
		/// <summary>
		/// N
		/// Description for IPS_GT16.XCXABGProyectoIPS.cardinalidad.N
		/// </summary>
		[DslDesign::DescriptionResource("IPS_GT16.XCXABGProyectoIPS.cardinalidad/N.Description", typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDomainModel), "IPS_GT16.XCXABGProyectoIPS.GeneratedCode.DomainModelResx")]
		N = 3,
	}
}

