//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS_GT16.XCXABGProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "XCXABG_DSLProyIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"XCXABGProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"IPS_GT16";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID XCXABGProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(XCXABGProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID XCXABGProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(XCXABGProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewXCXABGProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(XCXABGProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string XCXABGProyectoIPSPackageId = "f7d68baa-ba4b-41d7-90f5-cd3f8d879bac";
		
		// Editor factory identifier
		public const string XCXABGProyectoIPSEditorFactoryId = "decd6eae-5ab4-42bc-b330-fd5765e6bd3d";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string XCXABGProyectoIPSModelExplorerToolWindowId = "ff0d79c2-5163-4de3-b1ca-c00c11bba9cd";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace IPS_GT16.XCXABGProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string XCXABGProyectoIPSCommandSetId = "7e3770e1-b384-4572-aa41-6201f0cdc71b";
	}
}