//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\15.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideToolWindow(typeof(XCXABGProyectoIPSExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(XCXABGProyectoIPSExplorerToolWindow), Constants.XCXABGProyectoIPSEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@XCXABGProyectoIPSToolboxTab;IPS_GT16.XCXABGProyectoIPS.Dsl.dll", "IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSToolboxTab",
					"@EntidadToolboxItem;IPS_GT16.XCXABGProyectoIPS.Dsl.dll", 
					"IPS_GT16.XCXABGProyectoIPS.EntidadToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Entidad", 
					"@EntidadToolboxBitmap;IPS_GT16.XCXABGProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSToolboxTab",
					"@RelacionToolboxItem;IPS_GT16.XCXABGProyectoIPS.Dsl.dll", 
					"IPS_GT16.XCXABGProyectoIPS.RelacionToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Relacion", 
					"@RelacionToolboxBitmap;IPS_GT16.XCXABGProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSToolboxTab",
					"@EntidadRelacionToolboxItem;IPS_GT16.XCXABGProyectoIPS.Dsl.dll", 
					"IPS_GT16.XCXABGProyectoIPS.EntidadRelacionToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EntidadRelacion", 
					"@EntidadRelacionToolboxBitmap;IPS_GT16.XCXABGProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSToolboxTab",
					"@AtributoRelacionToolboxItem;IPS_GT16.XCXABGProyectoIPS.Dsl.dll", 
					"IPS_GT16.XCXABGProyectoIPS.AtributoRelacionToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AtributoRelacion", 
					"@AtributoRelacionToolboxBitmap;IPS_GT16.XCXABGProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSToolboxTab",
					"@AtributoEntidadToolboxItem;IPS_GT16.XCXABGProyectoIPS.Dsl.dll", 
					"IPS_GT16.XCXABGProyectoIPS.AtributoEntidadToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AtributoEntidad", 
					"@AtributoEntidadToolboxBitmap;IPS_GT16.XCXABGProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxItem("IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSToolboxTab",
					"@ClavePrimariaToolboxItem;IPS_GT16.XCXABGProyectoIPS.Dsl.dll", 
					"IPS_GT16.XCXABGProyectoIPS.ClavePrimariaToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ClavePrimaria", 
					"@ClavePrimariaToolboxBitmap;IPS_GT16.XCXABGProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideEditorFactory(typeof(XCXABGProyectoIPSEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(XCXABGProyectoIPSEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(XCXABGProyectoIPSEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"XCXABGProyectoIPS", typeof(XCXABGProyectoIPSEditorFactory))]

	internal abstract partial class XCXABGProyectoIPSPackageBase : DslShell::ModelingPackage
	{
		protected global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new XCXABGProyectoIPSEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			XCXABGProyectoIPSCommandSet commandSet = new XCXABGProyectoIPSCommandSet(this);
			commandSet.Initialize();
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			XCXABGProyectoIPSClipboardCommandSet clipboardCommandSet = new XCXABGProyectoIPSClipboardCommandSet(this);
			clipboardCommandSet.Initialize();
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(XCXABGProyectoIPSExplorerToolWindow));

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace IPS_GT16.XCXABGProyectoIPS
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDirectiveProcessor), global::IPS_GT16.XCXABGProyectoIPS.XCXABGProyectoIPSDirectiveProcessor.XCXABGProyectoIPSDirectiveProcessorName, "A directive processor that provides access to XCXABGProyectoIPS files")]
	[global::System.Runtime.InteropServices.Guid(Constants.XCXABGProyectoIPSPackageId)]
	internal sealed partial class XCXABGProyectoIPSPackage : XCXABGProyectoIPSPackageBase
	{
	}
}